# GOOGLE IT AUTOMATION WITH PYTHON - CENTRO DE GRADUADOS DE INGENIERIA DE LA UBA CON COURSERA


"""
CUESTIONARIO PRACTICO 1
¿ QUE ES UN PROGRAMA DE COPUTADORA ?
- A LIST OF INSTRUCTIONS
¿ QUE ES LA SINTAXIS DE UN LENGUAJE?
- THE RULES OF HOW TO EXPRESS
¿CUAL ES LA DIFERENCIA ENTRE UN PROGRAMA Y UN SCRIPT?
-THERE`S NOT MUCH DIFFERENCE
¿CUAL DE LOS ESCENARIOS SON BUENOS CANDIDATOS PARA AUTOMATIZACION?
- GENERATING A SALES REPORT, SPLIT REGION AND PRODUCT TYPE
- COPYING A FILE TO ALL COMPUTERS IN COMPANY
-SENDING PERSONALIZED EMAILS TO SUBSCRIBERS OF YOUR WEBSITE
¿WHAT ARE THE SEMANTICS WHEN APPLIED TO PROGRAMMING CODE AND PSEUDOCODE?
- THE EFFECT THE PROGRAMMING INSTRUCTION HAVE
#CUESTIONARIO PRACTICO 2
¿QUE SON LAS FUNCIONES?
-FUNCTIONS ARE PIECES OF CODE THAT PERFORM
¿ QUE SON LAS PALABRAS RESERVADAS?
- KEYWORDS ARE RESERVED WORDS THAT ARE USED TO CONSTRUCT INSTRUCTIONS
¿QUE HACE LA FUNCION PRINT()?
- THE PRINT FUNCTION OUTPITS MESSAGES TO THE SCREEN
¿?
-PRINT("PROGRAMMING IN PYTHON IS FUN!")
- CALCULAR EL CUADRADO
RATIO = X**((1+ 5**(1/2))/2)
PRINT(RATIO)

# CUESTIONARIO 3
- print("My first Python program")
- PYTHON ES UN PROGRAMA DE PROPOSITO GENERAL
- print("Have a nice day")
- 
for i in range(5):
  print("Python is fun")
-
for i in range(10):
  print(i)
- CARACTERISTICAS DE PYTHON
FACIL DE LEER Y ESCRIBIR
PODEMOS PRACTICAR PYTHON USANDO WEB O LOCALMENTE 
- COMPLETAR
color="yellow"
thnsg="sunshine"  
print(color+ " is the color of " + thing )
- CALCULAR LOS SEGUNDOS DE UNA SEMANA
print(7 * 864000)
- CUANTOS PASSWORD PODEMOS CALCULAR CON 6 LETRAS, por cada una hay 26 posibilidades
print(26**6)
"""